-- This is the sample code generated by AI Flow builder demo video
-- https://www.linkedin.com/posts/nick-akincilar-3417945_coco-text-audio-activity-7434251188855955456-wgmZ?utm_source=share&utm_medium=member_desktop&rcm=ACoAAAEBWeEBZtssnkUNTC2zIwH4PKbojVvcIFc


CREATE OR REPLACE STAGE AI_BUILDER.TEST.Incoming_files
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- 1. Create stream on stage
CREATE OR REPLACE STREAM AI_BUILDER.TEST.incoming_audio_files_STREAM
  ON STAGE AI_BUILDER.TEST.Incoming_files;

-- 2. Create landing table (directory table schema without metadata columns)
CREATE TABLE IF NOT EXISTS AI_BUILDER.TEST.incoming_audio_files (
  RELATIVE_PATH VARCHAR,
  SIZE NUMBER,
  LAST_MODIFIED TIMESTAMP_TZ,
  MD5 VARCHAR,
  ETAG VARCHAR,
  FILE_URL VARCHAR
);

-- 3. Create triggered task to process new files
CREATE OR REPLACE TASK AI_BUILDER.TEST.incoming_audio_files_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('AI_BUILDER.TEST.incoming_audio_files_STREAM')
AS
INSERT INTO AI_BUILDER.TEST.incoming_audio_files
SELECT
  RELATIVE_PATH,
  SIZE,
  LAST_MODIFIED,
  MD5,
  ETAG,
  FILE_URL
FROM AI_BUILDER.TEST.incoming_audio_files_STREAM
WHERE RELATIVE_PATH LIKE 'SampleAudio/%'
  AND RELATIVE_PATH LIKE '%%.mp3';

-- Resume task to start processing
ALTER TASK AI_BUILDER.TEST.incoming_audio_files_TASK RESUME;

-- 1. Create stream on stage
CREATE OR REPLACE STREAM AI_BUILDER.TEST.incoming_pdf_files_STREAM
  ON STAGE AI_BUILDER.TEST.Incoming_files;

-- 2. Create landing table (directory table schema without metadata columns)
CREATE TABLE IF NOT EXISTS AI_BUILDER.TEST.incoming_pdf_files (
  RELATIVE_PATH VARCHAR,
  SIZE NUMBER,
  LAST_MODIFIED TIMESTAMP_TZ,
  MD5 VARCHAR,
  ETAG VARCHAR,
  FILE_URL VARCHAR
);

-- 3. Create triggered task to process new files
CREATE OR REPLACE TASK AI_BUILDER.TEST.incoming_pdf_files_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('AI_BUILDER.TEST.incoming_pdf_files_STREAM')
AS
INSERT INTO AI_BUILDER.TEST.incoming_pdf_files
SELECT
  RELATIVE_PATH,
  SIZE,
  LAST_MODIFIED,
  MD5,
  ETAG,
  FILE_URL
FROM AI_BUILDER.TEST.incoming_pdf_files_STREAM
WHERE RELATIVE_PATH LIKE 'SampleDocs/%'
  AND RELATIVE_PATH LIKE '%%.pdf';

-- Resume task to start processing
ALTER TASK AI_BUILDER.TEST.incoming_pdf_files_TASK RESUME;

-- 1. Create stream on source table
CREATE STREAM IF NOT EXISTS AI_BUILDER.TEST.Audio_Transcript_STREAM
  ON TABLE AI_BUILDER.TEST.incoming_audio_files
  APPEND_ONLY = TRUE;

-- 2. Create target table (source columns + AI output column)
CREATE TABLE IF NOT EXISTS AI_BUILDER.TEST.Audio_Transcript (
  RELATIVE_PATH VARCHAR,
  SIZE NUMBER,
  LAST_MODIFIED TIMESTAMP_TZ,
  MD5 VARCHAR,
  ETAG VARCHAR,
  FILE_URL VARCHAR,
  transcript VARIANT,
  PROCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Create triggered task (ignoring metadata columns)
CREATE OR REPLACE TASK AI_BUILDER.TEST.Audio_Transcript_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('AI_BUILDER.TEST.Audio_Transcript_STREAM')
AS
INSERT INTO AI_BUILDER.TEST.Audio_Transcript (RELATIVE_PATH, SIZE, LAST_MODIFIED, MD5, ETAG, FILE_URL, transcript)
SELECT
  RELATIVE_PATH, SIZE, LAST_MODIFIED, MD5, ETAG, FILE_URL,
  SNOWFLAKE.CORTEX.AI_TRANSCRIBE(TO_FILE('@AI_BUILDER.TEST.Incoming_files', RELATIVE_PATH), {'timestamp_granularity': 'speaker'})
FROM AI_BUILDER.TEST.Audio_Transcript_STREAM;

-- Resume task to start processing
ALTER TASK AI_BUILDER.TEST.Audio_Transcript_TASK RESUME;

-- 1. Create stream on source table
CREATE STREAM IF NOT EXISTS AI_BUILDER.TEST.parsed_pdf_STREAM
  ON TABLE AI_BUILDER.TEST.incoming_pdf_files
  APPEND_ONLY = TRUE;

-- 2. Create target table (source columns + AI output column)
CREATE TABLE IF NOT EXISTS AI_BUILDER.TEST.parsed_pdf (
  RELATIVE_PATH VARCHAR,
  SIZE NUMBER,
  LAST_MODIFIED TIMESTAMP_TZ,
  MD5 VARCHAR,
  ETAG VARCHAR,
  FILE_URL VARCHAR,
  parsed_content VARIANT,
  PROCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Create triggered task (ignoring metadata columns)
CREATE OR REPLACE TASK AI_BUILDER.TEST.parsed_pdf_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('AI_BUILDER.TEST.parsed_pdf_STREAM')
AS
INSERT INTO AI_BUILDER.TEST.parsed_pdf (RELATIVE_PATH, SIZE, LAST_MODIFIED, MD5, ETAG, FILE_URL, parsed_content)
SELECT
  RELATIVE_PATH, SIZE, LAST_MODIFIED, MD5, ETAG, FILE_URL,
  SNOWFLAKE.CORTEX.PARSE_DOCUMENT('@AI_BUILDER.TEST.Incoming_files', RELATIVE_PATH, {'mode': 'LAYOUT', 'page_split': true})
FROM AI_BUILDER.TEST.parsed_pdf_STREAM;

-- Resume task to start processing
ALTER TASK AI_BUILDER.TEST.parsed_pdf_TASK RESUME;

-- 1. Create stream on source table
CREATE STREAM IF NOT EXISTS AI_BUILDER.TEST.audio_summary_STREAM
  ON TABLE AI_BUILDER.TEST.Audio_Transcript
  APPEND_ONLY = TRUE;

-- 2. Create target table (source columns + AI output column, excluding old PROCESSED_AT)
CREATE TABLE IF NOT EXISTS AI_BUILDER.TEST.audio_summary AS
SELECT * EXCLUDE (PROCESSED_AT), NULL::VARCHAR AS ai_summary, CURRENT_TIMESTAMP()::TIMESTAMP_LTZ AS PROCESSED_AT
FROM AI_BUILDER.TEST.Audio_Transcript WHERE 1=0;

-- 3. Create triggered task (ignoring metadata columns and old PROCESSED_AT)
CREATE OR REPLACE TASK AI_BUILDER.TEST.audio_summary_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('AI_BUILDER.TEST.audio_summary_STREAM')
AS
INSERT INTO AI_BUILDER.TEST.audio_summary
SELECT * EXCLUDE (PROCESSED_AT, METADATA$ACTION, METADATA$ISUPDATE, METADATA$ROW_ID), SNOWFLAKE.CORTEX.SUMMARIZE(transcript) AS ai_summary, CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM AI_BUILDER.TEST.audio_summary_STREAM;

-- Resume task to start processing
ALTER TASK AI_BUILDER.TEST.audio_summary_TASK RESUME;

-- 1. Create stream on source table
CREATE STREAM IF NOT EXISTS AI_BUILDER.TEST.parsed_pdf_pages_STREAM
  ON TABLE AI_BUILDER.TEST.parsed_pdf
  APPEND_ONLY = TRUE;

-- 2. Create target table for split pages
CREATE TABLE IF NOT EXISTS AI_BUILDER.TEST.parsed_pdf_pages (
  RELATIVE_PATH VARCHAR,
  PAGE_NUMBER INT,
  PAGE_TEXT VARCHAR,
  PROCESSED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Create triggered task to split pages
CREATE OR REPLACE TASK AI_BUILDER.TEST.parsed_pdf_pages_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('AI_BUILDER.TEST.parsed_pdf_pages_STREAM')
AS
INSERT INTO AI_BUILDER.TEST.parsed_pdf_pages (RELATIVE_PATH, PAGE_NUMBER, PAGE_TEXT)
SELECT 
  RELATIVE_PATH,
  f.index AS PAGE_NUMBER,
  f.value:content::STRING AS PAGE_TEXT
FROM AI_BUILDER.TEST.parsed_pdf_pages_STREAM,
LATERAL FLATTEN(input => parsed_content:pages) f;

-- Resume task to start processing
ALTER TASK AI_BUILDER.TEST.parsed_pdf_pages_TASK RESUME;

-- 1. Create stream on source table
CREATE STREAM IF NOT EXISTS AI_BUILDER.TEST.documents_final_STREAM
  ON TABLE AI_BUILDER.TEST.parsed_pdf_pages
  APPEND_ONLY = TRUE;

-- 2. Create target table (source columns + all AI output columns)
CREATE TABLE IF NOT EXISTS AI_BUILDER.TEST.documents_final AS
SELECT * EXCLUDE (PROCESSED_AT), NULL::VARCHAR AS ai_translated_spanish, NULL::FLOAT AS ai_sentiment_score, CURRENT_TIMESTAMP()::TIMESTAMP_LTZ AS PROCESSED_AT
FROM AI_BUILDER.TEST.parsed_pdf_pages WHERE 1=0;

-- 3. Create triggered task with CTEs to apply AI functions
CREATE OR REPLACE TASK AI_BUILDER.TEST.documents_final_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('AI_BUILDER.TEST.documents_final_STREAM')
AS
INSERT INTO AI_BUILDER.TEST.documents_final
WITH
  stream_data AS (
    SELECT * EXCLUDE (METADATA$ACTION, METADATA$ISUPDATE, METADATA$ROW_ID, PROCESSED_AT)
    FROM AI_BUILDER.TEST.documents_final_STREAM
  ),

  final_data AS (
    SELECT stream_data.*, SNOWFLAKE.CORTEX.TRANSLATE(PAGE_TEXT, 'en', 'es') AS ai_translated_spanish,
           SNOWFLAKE.CORTEX.SENTIMENT(PAGE_TEXT) AS ai_sentiment_score
    FROM stream_data
  )
SELECT *, CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM final_data;

-- Resume task to start processing
ALTER TASK AI_BUILDER.TEST.documents_final_TASK RESUME;

CREATE OR REPLACE CORTEX SEARCH SERVICE AI_BUILDER.TEST.my_doc_service
  ON PAGE_TEXT
  ATTRIBUTES PAGE_NUMBER, RELATIVE_PATH, ai_sentiment_score
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 hour'
  EMBEDDING_MODEL = 'snowflake-arctic-embed-m-v1.5'
  INITIALIZE = ON_SCHEDULE
  AS (
    SELECT * FROM AI_BUILDER.TEST.documents_final
  );

-- 1. Create stream on source table
CREATE STREAM IF NOT EXISTS AI_BUILDER.TEST.OUTPUT_TABLE_STREAM
  ON TABLE AI_BUILDER.TEST.parsed_pdf_pages
  APPEND_ONLY = TRUE;

-- 2. Create target table (source columns + all AI output columns)
CREATE TABLE IF NOT EXISTS AI_BUILDER.TEST.OUTPUT_TABLE AS
SELECT * EXCLUDE (PROCESSED_AT), NULL::VARCHAR AS ai_translated_spanish, NULL::VARIANT AS classification, CURRENT_TIMESTAMP()::TIMESTAMP_LTZ AS PROCESSED_AT
FROM AI_BUILDER.TEST.parsed_pdf_pages WHERE 1=0;

-- 3. Create triggered task with CTEs to apply AI functions
CREATE OR REPLACE TASK AI_BUILDER.TEST.OUTPUT_TABLE_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('AI_BUILDER.TEST.OUTPUT_TABLE_STREAM')
AS
INSERT INTO AI_BUILDER.TEST.OUTPUT_TABLE
WITH
  stream_data AS (
    SELECT * EXCLUDE (METADATA$ACTION, METADATA$ISUPDATE, METADATA$ROW_ID, PROCESSED_AT)
    FROM AI_BUILDER.TEST.OUTPUT_TABLE_STREAM
  ),

  ai_step_1 AS (
    SELECT *, SNOWFLAKE.CORTEX.TRANSLATE(PAGE_TEXT, 'en', 'es') AS ai_translated_spanish
    FROM stream_data
  ),

  ai_step_2 AS (
    SELECT *, SNOWFLAKE.CORTEX.CLASSIFY_TEXT(ai_translated_spanish, ARRAY_CONSTRUCT('positive', 'negative', 'neutral')) AS classification
    FROM ai_step_1
  )
SELECT *, CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM ai_step_2;

-- Resume task to start processing
ALTER TASK AI_BUILDER.TEST.OUTPUT_TABLE_TASK RESUME;
